const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
function load(file,deps={},extras={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,experimentalDecorators:true}}).outputText,{exports,require:name=>deps[name]??{},...extras});return exports;}
const {customerLocations}=load('src/app/core/customer-locations.ts');
test('completed customers deduplicate normalized name and exact point without exposing extra fields',()=>{const d={status:'DELIVERED',customerName:' Ana  Silva ',lat:0,lng:0,phone:'secret',notes:'secret'};const points=customerLocations([d,{...d,customerName:'ANA SILVA'},{...d,lat:.000001},{...d,status:'WAITING'},{...d,lat:NaN},{...d,lng:181},{...d,customerName:' '}]);assert.equal(points.length,2);assert.equal(points[0].deliveries,2);assert.equal(points[0].name,'Ana Silva');assert.deepEqual(Object.keys(points[0]).sort(),['deliveries','lat','lng','name']);});
function setup(fail=false){const markers=[];let cleared=0;const signal=v=>Object.assign(()=>v,{set:n=>v=n});const noop=()=>()=>{};const maps={importLibrary:async name=>name==='maps'?{Map:class{fitBounds(){} }}:{AdvancedMarkerElement:class{constructor(options){Object.assign(this,options);markers.push(this);}}},LatLngBounds:class{extend(){}},event:{clearInstanceListeners(){cleared++;},trigger(){}}};const deps={'@angular/core':{Component:noop,Input:noop,Output:noop,ViewChild:noop,signal,EventEmitter:class{emit(){}}},'../../core/customer-locations':{customerLocations},'../../core/google-maps':{GOOGLE_MAP_ID:'test',loadGoogleMaps:async()=>{if(fail)throw Error('missing key');return maps;}}};const {CustomerMapComponent}=load('src/app/components/customer-map/customer-map.component.ts',deps,{document:{createElement:()=>({style:{},append(){},setAttribute(){}})},ResizeObserver:class{observe(){}disconnect(){}}});const c=new CustomerMapComponent({run:fn=>fn(),runOutsideAngular:fn=>fn()});c.canvas={nativeElement:{}};return{c,markers,cleared:()=>cleared};}
test('Google customer markers use safe text and are removed on destroy',async()=>{const {c,markers,cleared}=setup();c.deliveries=[{status:'DELIVERED',customerName:'<img src=x>',lat:-19.7,lng:-47.9}];await c.ngAfterViewInit();assert.equal(markers.length,1);assert.equal(markers[0].title,'<img src=x> · 1 entrega(s)');assert.equal(markers[0].content.textContent,'🐺 <img src=x>');c.ngOnDestroy();assert.equal(markers[0].map,null);assert.equal(cleared(),2);});
test('Google loader error is visible and loading ends',async()=>{const {c}=setup(true);await c.ngAfterViewInit();assert.equal(c.loading(),false);assert.match(c.error(),/Google Maps/);});
test('customer map refresh removes obsolete markers when staff records disappear or fail',async()=>{const {c,markers}=setup();c.deliveries=[{status:'DELIVERED',customerName:'Ana',lat:1,lng:2}];await c.ngAfterViewInit();c.dataError='Permissão negada';c.ngOnChanges();assert.equal(markers[0].map,null);assert.equal(c.locations.length,0);});
test('legacy missing or malformed names are ignored without breaking map',()=>{assert.equal(customerLocations([{status:'DELIVERED',lat:0,lng:0},{status:'DELIVERED',lat:0,lng:0,customerName:42}]).length,0);});
